add scipy-typed output
conda-forge/scipy-stubs-feedstock pull request #5
Opened 2024-12-08 19:46 UTC by lucascolley

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-12-08 19:47 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12224737893) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12224737893](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12224737893). Examine the logs at this URL for more detail.</sub>

2024-12-08 19:49 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-12-08 19:55 UTC, lucascolley commented
@conda-forge-admin, please rerender

2024-12-08 19:57 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to rerender for you but ran into some issues. Please check the [output logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12224790519) of the GitHub Actions workflow below for more details. You can also ping `conda-forge/core` (using the `@` notation) for further assistance or you can try [rerendering locally](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-with-conda-smithy-locally).


The following suggestions might help debug any issues:
* Is the `recipe/{meta.yaml,recipe.yaml}` file valid?
* If there is a `recipe/conda-build-config.yaml` file in the feedstock make sure that it is compatible with the current [global pinnnings](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml).
* Is the fork used for this PR on an organization or user GitHub account? Automated rerendering via the webservices admin bot only works for user GitHub accounts.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12224790519](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12224790519). Examine the logs at this URL for more detail.</sub>

2024-12-08 20:03 UTC, lucascolley commented
@h-vetinari any idea why I'm seeing

```
    script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'PYTHON' is undefined
```

?

2024-12-08 21:12 UTC, jorenham commented on recipe/meta.yaml
> +{% set scipy_version = version.split('.')[:3] | join('.') %}
how about 
```suggestion
{% set scipy_version = version.rsplit('.', 1)[0] %}
```

2024-12-08 21:15 UTC, jorenham commented
What was this for, again 🤔 ?

2024-12-08 21:30 UTC, lucascolley commented
we're trying outputting `scipy-typed` from this feedstock, rather than the `scipy` one

2024-12-08 22:04 UTC, jorenham commented
> we're trying outputting `scipy-typed` from this feedstock, rather than the `scipy` one

hmm, I'm not sure what "outputting" means in this context 🤔

2024-12-08 22:17 UTC, lucascolley commented
one feedstock can output (onto the conda-forge channel) multiple packages. Right now `scipy-feedstock` outputs both `scipy` and `scipy-tests`. The proposed `scipy-typed` package could be output from any feedstock (once there is approval from https://github.com/conda-forge/admin-requests). I initially thought it would make sense to output it from `scipy-feedstock`, as I was in the same mental model as pip extras, but it might be easier recipe-wise to output it from `scipy-stubs-feedstock` instead. The only real difference is who has permission to merge PRs.

2024-12-08 22:23 UTC, jorenham commented
> one feedstock can output (onto the conda-forge channel) multiple packages. Right now `scipy-feedstock` outputs both `scipy` and `scipy-tests`. The proposed `scipy-typed` package could be output from any feedstock (once there is approval from https://github.com/conda-forge/admin-requests). I initially thought it would make sense to output it from `scipy-feedstock`, as I was in the same mental model as pip extras, but it might be easier recipe-wise to output it from `scipy-stubs-feedstock` instead. The only real difference is who has permission to merge PRs. Also, new builds of `scipy-typed` would line-up with new builds of `scipy-stubs` rather than new builds of `scipy`.

Ok thanks for explaining; I can see how it makes more sense this way 👌🏻

2024-12-08 22:30 UTC, h-vetinari commented
> any idea why I'm seeing [...]

`PYTHON` only gets populated if there's a `python` dependency. You've moved the dependencies to the output, but haven't moved the build-script (and actually, you should move the `python: noarch` too, and add it to `scipy-typed` as well).

Note that conda-recipes have an implicit "global" output (named after `package: name: ...`), and if this coincides with an output name, this results in very unintuitive behaviour (https://github.com/conda/conda-build/issues/4172). Standard fix is to rename the package-name into something not conflicting (e.g. `scipy-stubs-split`), and then add 

```diff
 extra:
   recipe-maintainers:
     - lucascolley
     - jorenham
+  feedstock-name: scipy-stubs
```

Sidenote: you should also get rid of the templating on `name` - it's completely pointless (the package name cannot be changed), and creates both extra mental overhead plus more opportunities for bugs.

PS. You'll also need to rename the script if you want to run it in the output itself (using `script: <xxx>.sh`), because `build.sh` is a reserved name that will _always_ be executed in the recipe-global build stage, which isn't doing anything here anymore.

PPS. There's a way to keep using the existing setup despite adding another output, but it's rather confusing, so I don't recommend doing it... It would entail adding a single-line `output: scipy-typed` (in this case explicitly repeating `package: name: ...`) like
```yaml
outputs:
  - name: scipy-stubs  # nothing else!
  - name: scipy-typed
    [...]  
```
but to actually test this output, you'd have to specify the `test:` section before `outputs:`.

2024-12-08 22:46 UTC, lucascolley commented
thanks for the explanations @h-vetinari ! I'll try to address those suggestions.

> Sidenote: you should also get rid of the templating on name - it's completely pointless (the package name cannot be changed), and creates both extra mental overhead plus more opportunities for bugs.

Makes sense 👍 pretty sure this is what grayskull generated for me.

2024-12-08 22:53 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found some lint.

Here's what I've got...


For **recipe/meta.yaml**:

 * ❌ The outputs section contained an unexpected subsection name. source is not a valid subsection name.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12225955566](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12225955566). Examine the logs at this URL for more detail.</sub>

2024-12-09 00:27 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-12-09 00:29 UTC, lucascolley commented
from investigating locally, it looks like `.mypyignore` is not included in the sdist on PyPI

2024-12-09 00:35 UTC, lucascolley commented
@jorenham perhaps we can add this?

```toml
[tool.hatch.build.targets.sdist]
include = [
    ".mypyignore",
]
```

It seems like hatch ignores dotfiles by default.

2024-12-09 01:11 UTC, lucascolley commented
I think I've made some progress, but I'd appreciate some further guidance @h-vetinari !

2024-12-09 06:51 UTC, h-vetinari commented on recipe/meta.yaml
> +      script: build-output.sh
```suggestion
    script: build-output.sh
    build:
      noarch: python
```

2024-12-09 07:01 UTC, h-vetinari commented on recipe/meta.yaml
> +    - mypyignore.patch
You could try building from a git tag, then the question of what gets installed through hatch by default goes away, and you can simply refer to `$SRC_DIR/path/to/file` if you need something.

2024-12-09 07:01 UTC, h-vetinari commented on recipe/meta.yaml
> +    - python
You don't need the "global" requirements section at all anymore (if you're not executing a `build.sh`)

2024-12-09 11:06 UTC, jorenham commented
> ```toml
> include = [
>     ".mypyignore",
> ]
> ```

That doesn't seem to work 🤔

2024-12-09 11:11 UTC, jorenham commented
> > ```toml
> > include = [
> >     ".mypyignore",
> > ]
> > ```
> 
> That doesn't seem to work 🤔

this works though

```toml
[tool.hatch.build.targets.sdist.force-include]
".mypyignore" = ".mypyignore"
```

2024-12-09 11:40 UTC, lucascolley commented on recipe/meta.yaml
> +    - python
Hmm, without this section I was still seeing the "undefined `PYTHON`" error

2024-12-09 15:33 UTC, lucascolley commented
locally, the build succeeds now, but I see

```
error: not checking stubs due to mypy build errors:
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_tukeylambda_stats.pyi: note: In function "tukeylambda_variance":
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_tukeylambda_stats.pyi:10:1: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
    def tukeylambda_variance(lam: onp.CanArray[_ShapeT, _DTypeLikeFloat_co]) -> onp.Array[_ShapeT, np.float64]: ...
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_tukeylambda_stats.pyi:10:1: note: Flipping the order of overloads will fix this error
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_tukeylambda_stats.pyi:10:1: note: See https://kotlinisland.github.io/basedmypy/_refs.html#code-overload-overlap for more info
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_tukeylambda_stats.pyi: note: In function "tukeylambda_kurtosis":
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_tukeylambda_stats.pyi:18:1: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
    def tukeylambda_kurtosis(lam: onp.CanArray[_ShapeT, _DTypeLikeFloat_co]) -> onp.Array[_ShapeT, np.float64]: ...
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_tukeylambda_stats.pyi:18:1: note: Flipping the order of overloads will fix this error
$PREFIX/lib/python3.13/site-packages/scipy-stubs/special/_orthogonal.pyi: note: In member "__call__" of class "orthopoly1d":
$PREFIX/lib/python3.13/site-packages/scipy-stubs/special/_orthogonal.pyi:83:5: error: Overloaded function signatures 2 and 4 overlap with incompatible return types  [overload-overlap]
        def __call__(self, /, v: onp.ToFloat) -> np.floating[Any]: ...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$PREFIX/lib/python3.13/site-packages/scipy-stubs/special/_orthogonal.pyi:85:5: error: Overloaded function signatures 3 and 4 overlap with incompatible return types  [overload-overlap]
        def __call__(self, /, v: onp.ToComplex) -> np.inexact[Any]: ...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_stats_py.pyi: note: In member "cdf" of class "_SimpleNormal":
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_stats_py.pyi:115:5: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
        def cdf(self, /, x: np.bool_ | np.uint8 | np.int8 | np.uint16 | np.int16 | np.float16 | np.float32) -> np.float32: ...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_stats_py.pyi:121:5: error: Overloaded function signatures 4 and 7 overlap with incompatible return types  [overload-overlap]
        def cdf(self, /, x: np.complex128 | np.clongdouble) -> np.complex64: ...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_stats_py.pyi: note: In member "sf" of class "_SimpleChi2":
$PREFIX/lib/python3.13/site-packages/scipy-stubs/stats/_stats_py.pyi:135:5: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [overload-overlap]
        def sf(self, /, x: float | np.float64 | np.uint64 | np.int64 | np.uint32 | np.int32 | np.bool_) -> np.float64: ...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Are those errors familiar Joren?

2024-12-09 15:45 UTC, lucascolley commented
@conda-forge-admin, please rerender

2024-12-09 15:52 UTC, h-vetinari commented on recipe/meta.yaml
> +    - python
Just use `python` directly, we don't need `{{ PYTHON }}`

2024-12-09 15:54 UTC, h-vetinari commented on recipe/meta.yaml
> +  git_url: https://github.com/jorenham/scipy-stubs.git
This is not what I meant by using the tag.
```suggestion
  url: https://github.com/jorenham/scipy-stubs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ...
```

2024-12-09 16:57 UTC, h-vetinari commented on recipe/build-output.sh
> +cp .mypyignore $SP_DIR
note that if you're using the tarball from the git tag, you don't need to actually install this file to run the tests. You can just ensure it's present in the test environment (as you're already doing with `source_files:`)

2024-12-09 17:01 UTC, h-vetinari commented
> locally, the build succeeds now, but I see

I suspect this has to do with the release of numpy 2.2, perhaps you still have 2.1 in your environment? 🤔

2024-12-09 17:01 UTC, h-vetinari commented
@conda-forge-admin, please rerender

2024-12-09 17:02 UTC, h-vetinari commented on recipe/mypyignore.patch
This file should be deleted now

2024-12-09 17:02 UTC, h-vetinari commented on recipe/build-output.sh
> +cp .mypyignore $SP_DIR
Once you get rid of this second step, you might as well move the single line invocation back to `meta.yaml`.

2024-12-09 17:04 UTC, lucascolley commented
> perhaps you still have 2.1 in your environment? 🤔

I was seeing the same errors as CI is now. [`scipy-stubs` CI](https://github.com/jorenham/scipy-stubs/actions/runs/12237067093/job/34131946979) is using `numpy==2.1.3`, so you're probably right

2024-12-10 02:13 UTC, jorenham commented
There's a bug in `stubtest` that's causing it to crash with `numpy==2.2.0`, see https://github.com/jorenham/scipy-stubs/pull/288 for the exact error in `scipy-stubs`, and https://github.com/KotlinIsland/basedmypy/pull/842 the proposed fix in `stubtest`

2024-12-15 23:42 UTC, lucascolley commented
locally I now see

```
+ stubtest --mypy-config-file=pyproject.toml --allowlist=.mypyignore --ignore-unused-allowlist scipy
error: scipy._lib.test_conda_forge_packaging failed to find stubs
```

which comes from https://github.com/conda-forge/scipy-feedstock/blob/9fe7f7450dc83b1b366dfafc3a335238103d1951/recipe/build-output.sh#L4-L9.

I guess we just want to add that to `.mypyignore`?

2024-12-15 23:43 UTC, jorenham commented
> There's a bug in `stubtest` that's causing it to crash with `numpy==2.2.0`, see [jorenham/scipy-stubs#288](https://github.com/jorenham/scipy-stubs/pull/288) for the exact error in `scipy-stubs`, and [KotlinIsland/basedmypy#842](https://github.com/KotlinIsland/basedmypy/pull/842) the proposed fix in `stubtest`

In the meantime the fix for this has been released in the new `2.8.1` version of `basedmypy`

2024-12-15 23:46 UTC, jorenham commented
> I guess we just want to add that to `.mypyignore`?

I guess? I'ts probably cleanest to put it in a another one though (you can pass multiple `--allowlist`)

2024-12-15 23:55 UTC, lucascolley commented
> (you can pass multiple --allowlist)

that is convenient 😄 let's see if this passes

2024-12-16 00:12 UTC, lucascolley commented
@conda-forge-admin, please rerender

2024-12-16 00:14 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to rerender for you, but it looks like there was nothing to do.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12343479817](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12343479817). Examine the logs at this URL for more detail.</sub>

2024-12-16 00:35 UTC, h-vetinari requested changes

2024-12-16 00:35 UTC, h-vetinari commented on recipe/meta.yaml
> +        - python
This (and all other bare uses of `python` as a dependency) needs `{{ python_min }}`, c.f. the linter and CFEP-25.

2024-12-16 00:35 UTC, h-vetinari commented on .ci_support/linux_64_.yaml
> +- 3.10.* *_cpython
As long as a rerender generates values for `python:` here, something is still not correct.

2024-12-16 12:10 UTC, lucascolley commented
@conda-forge-admin, please rerender

2024-12-16 12:16 UTC, lucascolley reviewed
thanks @h-vetinari , addressed

2024-12-16 12:16 UTC, lucascolley commented on README.md
> +numerical programming in modern Python.
any way to get rid of this duplication?

2024-12-16 12:27 UTC, h-vetinari commented on recipe/meta.yaml
>      test:
Not sure why the currently misses this output, but you should also add `python_min` under test.requires

2024-12-16 12:40 UTC, h-vetinari commented on recipe/.mypyignore-extra
> +scipy\._lib\.test_conda_forge_packaging
FWIW, I'll happily take PRs that make this test compatible with whatever basedmypy is doing.

2024-12-16 12:49 UTC, lucascolley commented
@conda-forge-admin, please rerender

2024-12-16 12:52 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to rerender for you, but it looks like there was nothing to do.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12353013891](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12353013891). Examine the logs at this URL for more detail.</sub>

2024-12-16 13:39 UTC, jorenham commented on recipe/.mypyignore-extra
> +scipy\._lib\.test_conda_forge_packaging
Hmm not sure what you mean @lucascolley 🤔

2024-12-16 13:44 UTC, lucascolley commented on recipe/.mypyignore-extra
> +scipy\._lib\.test_conda_forge_packaging
stubtest complains about no stubs for the script which scipy-feedstock adds, so instead of ignoring the file could we also annotate it inline? Or give it its own stub file? At first I wasn't sure whether it would pick up stubs for the import from scipy, but I think it should given that we have scipy-stubs installed at test-time.

2024-12-16 13:45 UTC, lucascolley commented on recipe/.mypyignore-extra
> +scipy\._lib\.test_conda_forge_packaging
either way that's a minor point and doesn't need to block this from being merged.

2024-12-16 14:36 UTC, jorenham commented on recipe/.mypyignore-extra
> +scipy\._lib\.test_conda_forge_packaging
Ah yea, sure. In that case, it should probably return `-> None`, as it doesn't *always* raise.

2024-12-16 14:39 UTC, jorenham commented on recipe/.mypyignore-extra
> +scipy\._lib\.test_conda_forge_packaging
And I agree that stubbing it instead of ignoring it would a nice flex

2024-12-18 11:30 UTC, lucascolley commented
@h-vetinari are you okay with me merging this now? I think it would be nice to be able to check that this all works before 1.15.0 is released.

2024-12-18 13:08 UTC, h-vetinari approved these changes

2024-12-18 13:13 UTC, merged

2024-12-18 13:13 UTC, lucascolley commented
thanks both!

2024-12-18 13:34 UTC, jorenham commented
Thanks @lucascolley ❤️